apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  labels:
    io.kompose.service: back
  name: back
spec:
  selector:
    matchLabels:
      io.kompose.service: back
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      labels:
        io.kompose.network/myapp: "true"
        io.kompose.service: back
    spec:
      containers:
      - image: aselzk/quotes-back:v2
        name: api
        envFrom:
        - secretRef:
            name: back-secret
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}

